<%@ Page Language="C#" AutoEventWireup="true" CodeFile="Gridviewexperiment.aspx.cs" Inherits="Gridviewexperiment" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
    <div>
    
        
        <br />
        <asp:MultiView ID="MultiView1" runat="server" ActiveViewIndex="0">
            <asp:View ID="View1" runat="server">
                <asp:GridView ID="GridView1" runat="server" AllowPaging="True" AllowSorting="True" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateSelectButton="True" DataKeyNames="student_id" DataSourceID="SqlDataSource1" OnSelectedIndexChanged="GridView1_SelectedIndexChanged">
            <Columns>
                <asp:CommandField ShowSelectButton="True" ButtonType="Image" EditImageUrl="~/images/AG00090_.GIF" SelectImageUrl="~/images/AG00092_.GIF" SelectText="Select Employee" ShowEditButton="True" />
                <asp:BoundField DataField="student_id" HeaderText="Student ID" ReadOnly="True" SortExpression="student_id" />
                <asp:BoundField DataField="student_name" HeaderText="Student Name" SortExpression="student_name" />
                <asp:BoundField DataField="student_marks" HeaderText="student_marks" SortExpression="student_marks" />
                <asp:BoundField DataField="u_id" HeaderText="u_id" SortExpression="u_id" />
                <asp:BoundField DataField="student_password" HeaderText="student_password" SortExpression="student_password" />
            </Columns>
            <RowStyle BackColor="#FFFFCC" BorderColor="#FF33CC" />
            <SelectedRowStyle BackColor="#000099" />
        </asp:GridView>
            </asp:View>
            <asp:View ID="View2" runat="server">


                  <asp:DetailsView ID="DetailsView1" runat="server" DataSourceID="SqlDataSource2" Height="50px" Width="125px">
                      <Fields>
                          <asp:CommandField ShowDeleteButton="True" ShowEditButton="True" ShowInsertButton="True" />
                      </Fields>
        </asp:DetailsView>
                  <br />
                  <asp:Button ID="Button1" runat="server" OnClick="Button1_Click" Text="Go back" />
            </asp:View>


        </asp:MultiView>
        <asp:SqlDataSource ID="SqlDataSource2" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>" DeleteCommand="DELETE FROM [student] WHERE [student_id] = @student_id" InsertCommand="INSERT INTO [student] ([student_id], [student_name], [student_marks], [u_id], [student_password]) VALUES (@student_id, @student_name, @student_marks, @u_id, @student_password)" SelectCommand="SELECT * FROM [student] where [student_id]=@student_id" UpdateCommand="UPDATE [student] SET [student_name] = @student_name, [student_marks] = @student_marks, [u_id] = @u_id, [student_password] = @student_password WHERE [student_id] = @student_id">
            <DeleteParameters>
                <asp:Parameter Name="student_id" Type="Int32" />
            </DeleteParameters>
            <InsertParameters>
                <asp:Parameter Name="student_id" Type="Int32" />
                <asp:Parameter Name="student_name" Type="String" />
                <asp:Parameter Name="student_marks" Type="Int32" />
                <asp:Parameter Name="u_id" Type="String" />
                <asp:Parameter Name="student_password" Type="String" />
            </InsertParameters>
            <SelectParameters>
                <asp:ControlParameter ControlID="GridView1" Name="student_id" PropertyName="SelectedValue" />
            </SelectParameters>
            <UpdateParameters>
                <asp:Parameter Name="student_name" Type="String" />
                <asp:Parameter Name="student_marks" Type="Int32" />
                <asp:Parameter Name="u_id" Type="String" />
                <asp:Parameter Name="student_password" Type="String" />
                <asp:Parameter Name="student_id" Type="Int32" />
            </UpdateParameters>
        </asp:SqlDataSource>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>" DeleteCommand="DELETE FROM [student] WHERE [student_id] = @student_id" InsertCommand="INSERT INTO [student] ([student_id], [student_name], [student_marks], [u_id], [student_password]) VALUES (@student_id, @student_name, @student_marks, @u_id, @student_password)" SelectCommand="SELECT * FROM [student]" UpdateCommand="UPDATE [student] SET [student_name] = @student_name, [student_marks] = @student_marks, [u_id] = @u_id, [student_password] = @student_password WHERE [student_id] = @student_id">
            <DeleteParameters>
                <asp:Parameter Name="student_id" Type="Int32" />
            </DeleteParameters>
            <InsertParameters>
                <asp:Parameter Name="student_id" Type="Int32" />
                <asp:Parameter Name="student_name" Type="String" />
                <asp:Parameter Name="student_marks" Type="Int32" />
                <asp:Parameter Name="u_id" Type="String" />
                <asp:Parameter Name="student_password" Type="String" />
            </InsertParameters>
            <UpdateParameters>
                <asp:Parameter Name="student_name" Type="String" />
                <asp:Parameter Name="student_marks" Type="Int32" />
                <asp:Parameter Name="u_id" Type="String" />
                <asp:Parameter Name="student_password" Type="String" />
                <asp:Parameter Name="student_id" Type="Int32" />
            </UpdateParameters>
        </asp:SqlDataSource>
        <br />
      
        <br />
        <br />
    
    </div>
    </form>
</body>
</html>